on: push

name: typecheck
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: yarn install
      - run: yarn typecheck
